### PR TITLE
Add "dmd-" prefix for DMD

### PR DESCRIPTION
**Pull request by tom-tan**
This request is to use `dmd-` prefix for DMD compilers to make consistent with `ldc-` prefix for LDC.
After merging this request, we can use `dmd-2.068.1` instead of `2.068.1` to install DMD compilers.

This request will not break any commands for already installed DMD compiler such as `2.068.1`
because `denv versions` and other commands only see the directories in `denv/versions`.

### CODE REVIEW

**Comment by tom-tan** [comment]
ping!

**Comment by repeatedly** [comment]
Good idea. I will check it later.
Please wait.

**Comment by tom-tan** [comment]
I rebased and added dmd-2.068.2.

**Comment by repeatedly** [comment]
Seem ok. Merged!

**Comment by tom-tan** [comment]
Thanks!

**Pull request merged**
